# Generated by Django 3.2.7 on 2021-09-14 07:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999999999999)])),
                ('product_name', models.CharField(max_length=500)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('times_searched_anonymous', models.PositiveIntegerField(default=0)),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.brand')),
            ],
        ),
    ]
